version: "3"
services:
  server:
   image: ms-persistencia
   ports:
    - "8081:8081"
   environment:
    - spring.datasource.url=jdbc:mysql://mysqldb:30363/test?useSSL=false
   networks:
    - springmysql-net
   depends_on:
    - mysqldb
    
  mysqldb:
   image: mysql:5.7
   networks:
    - mired
   environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=test
    - MYSQL_USER=root
    - MYSQL_PASSWORD=secret
    
   
   	