version: '3'

services:
  docker-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=test
      - MYSQL_USER=sys
      - MYSQL_PASSWORD=1234
    ports:
      - 3306:3306

  persistencia-app:
    image: ms-persistencia:latest
    ports:
       - 8081:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/test?autoReconnect=true&useSSL=false
    depends_on:
       - docker-mysql
       
       

